---
- name: Setup Docker
  hosts: all
  gather_facts: false
  remote_user: daniel

  tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - ca-certificates
        - curl

    - name: Add keyring directory if not already exists
      become: true
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
      register: keyring_folder
      changed_when: keyring_folder != 0

    - name: Download Dockers official GPG key
      become: true
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/debian/gpg"
        dest: "/etc/apt/keyrings/docker.asc"
        mode: '0644'

    - name: Gather system facts
      become: true
      ansible.builtin.setup:
        filter:
          - 'ansible_architecture'
          - 'ansible_distribution_release'

    - name: Add Docker source
      become: true
      ansible.builtin.template:
        src: docker.list.j2
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'
      vars:
        arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
        codename: "{{ ansible_distribution_release | lower }}"

    - name: Install Docker packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add user to docker group
      become: true
      ansible.builtin.user:
        name: daniel
        groups: docker
        append: true
