http:
 #region routers 
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.home.wollbro.se`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.home.wollbro.se`)"
      middlewares:
        - redirectregex-pihole
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole
    truenas:
      entryPoints:
        - "https"
      rule: "Host(`nas.home.wollbro.se`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: truenas
    jellyfin:
      entryPoints:
        - "https"
      rule: "Host(`media.wollbro.se`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: jellyfin
    minio:
      entryPoints:
        - "https"
      rule: "Host(`minio.home.wollbro.se`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: minio
    s3:
      entryPoints:
        - "https"
      rule: "HostRegexp(`{subdomain:[a-z0-9_-]+}.s3.wollbro.se`) || Host(`s3.wollbro.se`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: s3
    portainer:
      entryPoints:
        - "https"
      rule: "Host(`portainer.home.wollbro.se`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: portainer
    homepage:
      entryPoints:
        - "https"
      rule: "Host(`home.wollbro.se`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: homepage
    # rancher:
    #   entryPoints:
    #     - "https"
    #   rule: "Host(`rancher.home.wollbro.se`)"
    #   middlewares:
    #     - default-headers
    #     - https-redirectscheme
    #   tls: {}
    #   service: rancher

#endregion
#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.50.61:8006"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.50.13:80"
        passHostHeader: true
    truenas:
      loadBalancer:
        servers:
          - url: "https://192.168.50.107"
        passHostHeader: true
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.50.29:8096"
        passHostHeader: true
    minio:
      loadBalancer:
        servers:
          - url: "http://192.168.50.107:9002/"
        passHostHeader: true
    s3:
      loadBalancer:
        servers:
          - url: "http://192.168.50.107:9000/"
        passHostHeader: true
    portainer:
      loadBalancer:
        servers:
          - url: "https://192.168.50.29:9443/"
        passHostHeader: true
    homepage:
      loadBalancer:
        servers:
          - url: "http://192.168.50.29:3000/"
        passHostHeader: true
    # rancher:
    #   loadBalancer:
    #     servers:
    #       - url: "https://192.168.50.107"
    #     passHostHeader: true

#endregion
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    redirectregex-pihole:
      redirectRegex:
        regex: "/admin/(.*)"
        replacement: /

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    idrac:
      headers:
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "192.168.50.0/24"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers