---
- name: Change user password
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: username
      prompt: "Username"
      private: false

    - name: new_password
      prompt: "Enter new password"

    - name: confirm_password
      prompt: "Confirm new password"

  tasks:
    - name: Confirm entered passwords
      ansible.builtin.fail:
        msg: "Passwords did not match each other, Please try again!"
      when: new_password != confirm_password

    # Package passlib is needed to encrypt passwords
    - name: Install required apt packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: present
        name: "{{ item }}"
      loop:
        - python3-passlib

    - name: Set new password
      become: true
      ansible.builtin.user:
        user: "{{ username }}"
        update_password: always
        password: "{{ new_password | password_hash('sha512') }}"
