---
- name: Setup GitHub Actions Runner
  hosts: all
  gather_facts: false
  remote_user: daniel

  vars:
    github_runner_version: '2.313.0'

  tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - git
        - curl
        - jq
        - unzip
        - ansible # This is needed for some ansible scripts that is run by the worker

    - name: Create directory for runner
      become: true
      ansible.builtin.file:
        path: /opt/github-runner
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Download GitHub Actions Runner
      become: true
      ansible.builtin.get_url:
        url: "https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/actions-runner-linux-x64-{{ github_runner_version }}.tar.gz"
        dest: /opt/github-runner/actions-runner.tar.gz
        mode: '0644'

    - name: Extract GitHub Actions Runner
      become: true
      ansible.builtin.unarchive:
        src: /opt/github-runner/actions-runner.tar.gz
        dest: /opt/github-runner
        remote_src: true

    - name: Configure GitHub Actions Runner
      ansible.builtin.shell: |
        ./config.sh --url {{ github_repository_url }} \
                   --token {{ github_token }} \
                   --name {{ runner_name | default('runner') }} \
                   --runnergroup {{ runner_group | default('default') }} \
                   --labels {{ runner_labels | default('self-hosted') }} \
                   --unattended
      register: config_output
      changed_when: config_output != 0
      args:
        chdir: /opt/github-runner

    - name: Install GitHub Actions Runner as a Service
      become: true
      ansible.builtin.shell: |
        ./svc.sh install
      register: service_installed_output
      changed_when: service_installed_output != 0
      args:
        chdir: /opt/github-runner

    - name: Start GitHub Actions Runner Service
      become: true
      ansible.builtin.shell: |
        ./svc.sh start
      register: service_started_output
      changed_when: service_started_output != 0
      args:
        chdir: /opt/github-runner

    - name: Add PPA to system
      become: true
      ansible.builtin.command: |
        "curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
      register: ppa_added
      changed_when: ppa_added != 0

    - name: Install nodejs
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - nodejs

  vars_prompt:
    - name: github_repository_url
      prompt: "GitHub Repository URL (e.g., https://github.com/yourusername/yourrepository)"
      private: false

    - name: github_token
      prompt: "GitHub Token with Repo scope"
      private: true

    - name: runner_name
      prompt: "Runner Name (default: runner)"
      private: false

    - name: runner_group
      prompt: "Runner Group (default: default)"
      private: false

    - name: runner_labels
      prompt: "Runner Labels (comma-separated, default: self-hosted)"
      private: false
