---
- name: Install/Update portainer
  hosts: all
  remote_user: daniel

  tasks:
    - name: Add service folder with config folder
      ansible.builtin.shell: |
        install -m 0755 -d services/portainer
      register: service_folder
      changed_when: service_folder != 0

    - name: Add compose file
      ansible.builtin.copy:
        src: ../docker/docker-compose.yml
        dest: "{{ ansible_env.HOME }}/services/portainer/docker-compose.yml"
        mode: "0755"
        remote_src: false

    - name: Recreate containers
      ansible.builtin.command: |
        docker compose -f {{ ansible_env.HOME }}/services/portainer/docker-compose.yml up -d
      register: docker_compose
      changed_when: docker_compose != 0
